config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bands do
    resources :friends
    resources :comments
    resources :posts
    resources :shows
  end

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :load_commentable
  before_action :find_comment, only: [:edit, :update, :destroy ]
  before_action :find_band, except: :create

  def index
    @comments = @commentable.comments
  end

  def show
  end

  def new
    @comment = @commentable.comments.new
  end

  def edit
  end

  def create
    @comment = @commentable.comments.new(comment_params)

    unless verify_recaptcha?(params[:recaptcha_token], 'comment')
      flash.now[:error] = "reCAPTCHA Authorization Failed. Please try again later."
      return render :new
    else
      
    end

    if @comment.save
      redirect_to @commentable, notice: 'Comment created'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @band, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @band, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def load_commentable
      resource, id = request.path.split('/')[1,2]
      @commentable = resource.singularize.classify.constantize.find(id)
    end

    def comment_params
      params.require(:comment).permit(:body, :username, :image, :commentable_type, :commentable_id)
    end

    def find_band
      @band = Band.find_by(id: params[:band_id])
    end

    def find_comment
      @comment = Comment.find_by(id: params[:id])
    end
end

app/views/comments/_form.html.erb
<%= content_for :recaptcha_js do %>
  <%= include_recaptcha_js %>
<% end %>

<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.text_field :image, placeholder: "Link to your profile picture" %>
  </div>

  <div class="field">
    <%= f.text_field :username, placeholder: "Username" %>
  </div>

  <div class="field">
    <%= f.text_area :body, rows: 5, placeholder: "Write your comment here" %>
  </div>

  <div class="actions">
    <%= f.submit "Save" %>
  </div>

  <%= recaptcha_execute('comment') %>
<% end %>

app/views/comments/_show.slim
.comments
  .secondary-light
    h2 #{@band.name}'s Friends Comments
  b Displaying 50 of 34234 comments (View/Edit All Comments)
  - if has_comments?
    table.secondary
      - @band.comments.each do |comment|
        tr
          td.secondary-med
            h4.friend-name= comment.username
            img[src="#{comment.image}" class='friend-img']
          td.secondary-light
            - if user_signed_in? && is_masc?
              h4 = link_to "Edit", edit_band_comment_path(@band, comment)
              h4 = link_to "Delete", band_comment_path(@band, comment), :data => {:confirm => 'Are you sure you want to delete your comment?'}, :method => :delete
            p
              b= comment.created_at.strftime("%m/%m/%Y%l:%M%p")
            = comment.body

  - else
    p No one has left a comment
h4#add-comment Add Comment
.new-comment
  .secondary-light
    h2 Add a Comment
  .secondary-light
    = render 'comments/form'

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', band_path(params[:band_id]) %>