config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bands do
    resources :friends
    resources :comments
    resources :posts
    resources :shows
  end

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :comments, as: :commentable
  has_many :friends
  has_many :posts
  has_many :shows
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :find_band, except: :create

  def show
    @songs = get_list(path = "/dawsonscreamo")
    @commentable = @band
    @comments = @commentable.comments
    @comment = Comment.new
    @ordered_friends = @band.friends.order(:order)
  end

  def edit
  end

  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.'}
      else
        format.html { render :edit }
      end
    end
  end

  private

  def find_band
    @band = Band.find_by(id: params[:id])
  end

  def band_params
    params.require(:band).permit(:name, :photo, :genre, :location, :email, :member_since, :influences, :sounds_like, :record_label, :type_of_label, :profile_views, :last_login, :css, :javascript, :cover_art, :band_members)
  end
end

app/helpers/band_helper.rb
module BandHelper
	def has_comments?
		!@band.comments.empty?
	end

	def has_friends?
		!@band.friends.empty?
	end

  def has_posts?
    !@band.posts.empty?
  end
end

app/views/bands/_audio.slim
.container
  #mainwrap
    .audio-top
      .audiowrap
        #audio0
          audio#audio1[preload controls="controls"]
            | Your browser does not support HTML5 Audio!
        #tracks
          = image_tag("audio/stop", id: "stop-btn")
          a#btnPrev
            = image_tag("audio/prev", id: "prev-btn")
          = image_tag("audio/pause", id: "pause-btn")
          = image_tag("audio/play", id: "play-btn")
          a#btnNext
            = image_tag("audio/next", id: "next-btn")
        .volume-container
          .volume-icon
            = image_tag("audio/volume-icon", id: "volume-icon")
          .volume
            input[type="range" id="volume-seek" value="5" max="10"]
            = image_tag("audio/volume-indicator", id: "volume-indicator")
      .audiowrap
        .playing-container
          marquee[behavior='alternate' scrollamount='2' id='npTitle']
          .band-name= @band.name.upcase
          #npAction
            span paused
        span 00:50
        input[type="range" id="track-seek" value="0" max=""]
        .row
          .bar
          .bar
          .bar
          .bar
          .bar
    #totalplays
      span Total Plays: 23432141
      span Downloads Today: 0
      span Plays Today: 1

    #plwrap
      .cover-art
        img[src="#{@band.cover_art}"]
      ul#plList
        .playlist-additions
          = image_tag("logo/masc4masclogo2.png", class: "white-logo")
          .stand-alone STANDALONEPLAYER

  ul#songData
    - @songs.links.each do |song|
      li[data-song-name=song.name data-song-url=song.url.sub!('dropbox.com', 'dl.dropboxusercontent.com')]
  ul#plList

app/views/bands/_form.slim
h1 Editing Band
=form_for @band do |f|
  .container
    =f.label :name
    =f.text_field :name

    =f.label :photo
    =f.text_field :photo

    =f.label :genre
    =f.text_field :genre

    =f.label :location
    =f.text_field :location

    =f.label :email
    =f.text_field :email

    =f.label :member_since
    =f.text_field :member_since

    =f.label :influences
    =f.text_field :influences

    =f.label :sounds_like
    =f.text_field :sounds_like

    =f.label :record_label
    =f.text_field :record_label

    =f.label :type_of_label
    =f.text_field :type_of_label

    =f.label :profile_views
    =f.number_field :profile_views

    =f.label :last_login
    =f.text_field :last_login

    =f.label :cover_art
    =f.text_field :cover_art

    =f.label :band_members
    =f.text_field :band_members
  .container
    =f.label :css
    =f.text_area :css, rows: 20

    =f.label :javascript
    =f.text_area :javascript, rows: 20
  .container.submit-btn
    =f.submit "Save"

app/views/bands/edit.slim
#band-edit-page
  - if user_signed_in? && is_masc?
    = render 'form', band: @band
  - else
    p You must be a band member to view this page.

app/views/bands/show.slim
main
	.left-container
		.band-show
			section.band-container
				h1= @band.name
				b= @band.genre
				.band-info
					.band-img-container
						img[class="band-img" src="#{@band.photo}"]
						.band-status
							p= @band.location
							p Profile Views: #{@band.profile_views}
							p Last Login: #{@band.last_login}
		table.primary.contact-info
			h2.primary-dark Contacting #{@band.name}
			tr
				td= link_to(image_tag("contact/sendMail", title: "Send Message"), 'mailto: masc4mascbandemail@gmail.com')
				td= link_to(image_tag("contact/forwardFriend", title: "Forward to Friend"), 'mailto: masc4mascbandemail@gmail.com')
			tr
				td= link_to(image_tag("contact/addFriend", title: "Add to Friends"), 'mailto: masc4mascbandemail@gmail.com')
				td= link_to(image_tag("contact/addFavorites", title: "Add to Favorites"), 'mailto: masc4mascbandemail@gmail.com')
			tr
				td= link_to(image_tag("contact/instantMessage", title: "Instant Message"), 'mailto: masc4mascbandemail@gmail.com')
				td= link_to(image_tag("contact/blockUser", title: "Block User"), 'mailto: masc4mascbandemail@gmail.com')
			tr
				td= link_to(image_tag("contact/addGroup", title: "Add to Group"), 'mailto: masc4mascbandemail@gmail.com')
				td= link_to(image_tag("contact/rankUser", title: "Rank User"), 'mailto: masc4mascbandemail@gmail.com')
		table.primary.general-info
			h2.primary-dark #{@band.name} General Info
			tr
				td.primary-med
					h3 Member Since
				td.primary-light #{@band.member_since}
			tr
				td.primary-med
					h3 Band Members
				td.primary-light #{@band.band_members}
			tr
				td.primary-med
					h3 Influences
				td.primary-light #{@band.influences}
			tr
				td.primary-med
					h3 Sounds Like
				td.primary-light #{@band.sounds_like}
			tr
				td.primary-med
					h3 Record Label
				td.primary-light #{@band.record_label}
			tr
				td.primary-med
					h3 Type of Label
				td.primary-light #{@band.type_of_label}

	.right-container
		.audio-container
				= render "audio"
		- if @band.shows.length > 0
			table.primary.upcoming-shows
				h2.primary-dark Upcoming Shows
				- @band.shows.each do |show|
					tr
						td.primary-med= show.date
						td.primary-light= show.time
						td.primary-light= show.name
						td.primary-light= show.location
						- if user_signed_in? && is_masc?
							td.primary-light= link_to "Edit", edit_band_show_path(@band, show)
							td.primary-light= link_to "Delete", band_show_path(@band, show), :data => {:confirm => 'Are you sure you want to delete your show?'}, :method => :delete
		- if user_signed_in? && is_masc?
			p.new-show= link_to "New Show", new_band_show_path(@band)
		section
			= render 'posts/index'
		section
			.secondary-light
				h2 #{@band.name}'s Friend Space
			b #{@band.name} has 14214 friends.
			.friends
				- if has_friends?
					- @ordered_friends.each do |friend|
						.friend
							h4.friend-name= friend.name
							img[class="friend-img" src="#{friend.image}"]
							- if user_signed_in? && is_masc?
								= link_to "Edit", edit_band_friend_path(@band, friend)
								= link_to "Delete", band_friend_path(@band, friend), :data => {:confirm => 'Are you sure you want to delete your friend?'}, :method => :delete
				- else
					.band-friend
						h4 Tom
						img[class="friend-img" src="https://a3-images.myspacecdn.com/images03/1/240e42b5d9ce48a78983961e7fcb3c39/300x300.jpg"]
				- if user_signed_in? && is_masc?
					p.new-friend= link_to "New Friend", new_band_friend_path(@band)

		= render 'comments/show'