config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bands do
    resources :friends
    resources :comments
    resources :posts
    resources :shows
  end

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, as: :commentable
  belongs_to :band
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :find_band
  # GET /posts
  # GET /posts.json
  def index
    @posts = @band.posts.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @band.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @band, notice: 'Post was successfully created.' }
        format.json { render :post, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @band, notice: 'Post was successfully updated.' }
        format.json { render :post, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to @band, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def find_band
      @band = Band.find_by(id: params[:band_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@band, post] do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_index.slim
.blog
  b #{@band.name}'s Latest Blog Entry
  - if has_posts?
    - @band.posts.each do |post|
      .blog-post
        = post.title + " ("
        a[href=band_post_path(@band, post) class='blog-post-link'] view more
        span )
        - if user_signed_in? && is_masc?
          = link_to 'Edit', edit_band_post_path(@band, post)
          = link_to 'Delete', band_post_path(@band, post), method: :delete, data: { confirm: 'Are you sure?' }
        br
  - else
    p There's nothing here yet
  - if user_signed_in? && is_masc?
    = link_to 'New Post', new_band_post_path(@band)

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.slim
section
  .blog-post
    - if user_signed_in? && is_masc?
      = link_to "Edit", edit_band_post_path(@band, @post)
      = link_to "Delete", band_post_path(@band, @post), :data => {:confirm => 'Are you sure you want to delete your post?'}, :method => :delete
    p
      b= @post.title
    p Published: #{@post.created_at.strftime("%A, %d %b %Y %l:%M %p")}
    p
      =@post.body